languageCode = 'en-GB'
title = 'John Taylor'

[params]
  description = "The work of the Glasgow based artist John Taylor"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[imaging]
  quality = "75"
  resampleFilter = "Lanczos"
[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[module]
# replacements = 'github.com/glasgowartist/ga-hugo -> ../../ga'

[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = 'github.com/glasgowartist/ga-hugo'

  [[imports.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[imports.mounts]]
    source = "assets"
    target = "assets"

  [[imports.mounts]]
    source = "content"
    target = "content"

  [[imports.mounts]]
    source = "layouts"
    target = "layouts"

  [[imports.mounts]]
    source = "static"
    target = "static"
